"""
class Notification, it sends email notification when a trade
is generated by the trading strategy.
"""

import configparser as ConfigParser
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

class Notification:
    def __init__(self, subject:str):
        configParser = ConfigParser.RawConfigParser()
        configParser.read('config.cfg')
        self.sender_address = str(configParser.get('email', 'sender_address'))
        self.sender_pass = str(configParser.get('email', 'sender_pass'))
        self.receiver_address = str(configParser.get('email', 'receiver_address'))
        self.init_email(subject)
        self.init_session()

    def init_email(self, subject:str):
        self.message = MIMEMultipart()
        self.message['From'] = 'My Trading System'
        self.message['To'] = self.receiver_address
        self.message['Subject'] = subject
        self.message['X-Priority'] = '2'

    def init_session(self):
        #Create SMTP session for sending the mail
        self.session = smtplib.SMTP('smtp.gmail.com', 587)
        # Enable Security (TLS)
        self.session.starttls()
         # Login with email_id and password
        self.session.login(self.sender_address, self.sender_pass)

    def send_notification(self, message:str):
        self.message.attach(MIMEText(message, 'plain'))
        text = self.message.as_string()
        self.session.sendmail(self.sender_address, self.receiver_address, text)

    def stop_session(self):
        self.session.quit()

mail_content = '''Greetings,
This is a simple mail. The mail is sent using Python SMTP library.

Regards,
ABC
'''
